export { default as About } from './About'
export { default as Blog } from './Blog'
export { default as Contact } from './Contact'
export { default as Courses } from './Courses'
export { default as Home } from './Home'