export { default as About } from './About'
export { default as Blog } from './Blog'
export { default as Contact } from './Contact'
export { default as Courses } from './Courses'
export { default as Home } from './Home'
export { default as Navbar } from './global/Navbar'
export { default as Footer } from './global/Footer'